image: 172.16.1.99/transwarp/ockle/builder/centos7:trunk
before_script:
    - source /etc/profile
    - source /root/.bashrc

stages:
   - postcommit_build

postcommit_build:
  stage: postcommit_build
  script:
    - set -e
    - pip install -i http://172.16.1.161:30033/repository/pypi/simple/ --trusted-host 172.16.1.161 -U twine
    - pip install -r requirements.txt -i http://172.16.1.161:30033/repository/pypi/simple/ --trusted-host 172.16.1.161
    - python setup.py sdist
    - twine upload --repository-url http://172.16.1.161:30033/repository/pypi-local/ dist/*  -u admin -p admin123
  only:
      - master@TDC/verminator
  tags:
    - k8s
